#!/bin/sh

# PROVIDE: btcd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=btcd
rcvar=btcd_enable

btcd_user="bitcoin"
btcd_group="bitcoin"
command="/home/bitcoin/btcd-freebsd-amd64-v0.24.0/${name}"

command_args="-C /home/bitcoin/.btcd/btcd.conf > /dev/null 2>&1 &"

required_files="/home/bitcoin/.btcd/btcd.conf"

load_rc_config $name
run_rc_command "$1"
